### ISSUE TITLE
Can't find Jedi

### ISSUE THREAD

**Issue by hbridge** [tinloaf/autocomplete-plus-python-jedi#17]
I've installed autocomplete-plus and autocomplete-plus-python-jedi, but as soon as I start typing in a python file I get this dialog.

![screen shot 2015-04-30 at 5 54 44 pm](https://cloud.githubusercontent.com/assets/77620/7423336/409ec0dc-ef62-11e4-91bf-1d1033d48f02.png)

Even though I know it's bundled with the package, I also pip installed jedi but I still get the error.  Any ideas?

**Comment by tinloaf** [comment]
That looks like... OS X? How do you start Atom, from the command line or by clicking on something? Can you try this:

Open a console, start python by typing 'python'. Inside python, verify that jedi is present by doing 'import jedi'. If that works, start atom _from that console_. Is it still unable to find jedi?

**Comment by hbridge** [comment]
Thanks tinloaf, yes I'm on OS X Yosemite.  Running it from the console fixes the issue, but I usually run from the Dock/Search.  Is there something I can add to an atom config file to make that work?

**Comment by tinloaf** [comment]
I'm not sure how a python installation works on OS X. It looks like the default python environment (which applies to your Atom when started from the Dock) is not the same as the environment in a console - and the environment that Atom is started in does not include jedi. If you can install Jedi in that environment, everything should be fine. Or if you're able to make the Atom launcher in your dock switch to the correct python environment.

But since I've never used OS X, I'm at a loss how to do so, sorry.

**Comment by hbridge** [comment]
ok thanks, appreciate the help.

**Comment by ghost** [comment]
I get this issue on Linux. If I install jedi into my virtualenv and open atom from an env-activated terminal then it works, but it does not seem to find the bundled package. It doesn't find the bundled one whether or not a click a launcher or run from CLI. Is the bundled package just broken?

**Comment by henworth** [comment]
I had this same problem on OS X Yosemite, what worked for me was changing this line to reference the full path to a python binary:

https://github.com/tinloaf/autocomplete-plus-python-jedi/blob/81a39eb18c61bc1a2fde7d5c5947c31b02708efa/lib/jedi-provider.coffee#L73

What I believe was happening (at least in my case) was Atom was using the system (default) python rather than the one I installed using brew. This python does not have the jedi module installed, but the brew installed version does. Changing that path to the location of the brew installed python fixed the issue. That doesn't explain why the built-in jedi module isn't working though.

Would it be worth adding a config setting for a python executable path? I've added one to my local install and I would be willing to submit a PR if this feature is wanted.

**Comment by ghost** [comment]
I feel like this package is not the correct one to add a Python path. I wonder why such a setting doesn't exist in the language package? (Probably because it never actually runs Python...). I guess the reason is obvious, but there should be a central way to define your default Python installation, because other packages should be able take advantage of a centrally defined Python installation (virtualenv, script, for example...neither of these will do the correct thing in some cases, with your current setup, I think).

Edit: Actually I think rgbkrk/atom-script#5 is the same issue as the Mac/brew issue.

**Comment by awatts** [comment]
I'm having this problem on OS X (10.9.5) too. I have several Pythons installed; I use Anaconda in general, but some HomeBrew thing pulled Python in as a dependency, plus there's the system Python, and sometimes I'm starting Atom from the command line in a virtualenv. I have no idea which one it's trying to find Jedi in. It would help if the error noted the path the Python executable it's trying or if as @henworth said, you could tell it which one to use.

**Comment by muppetjones** [comment]
I changed the line referenced by @henworth (specifically 'python' to 'python3'), and it worked fine. I installed jedi in my homebrew-installed python3.

**Comment by henworth** [comment]
The issue @saiyr linked to provides a potential workaround. Adding this to Atom's init script:

`process.env.PATH = ["/usr/local/bin", process.env.PATH].join(":")`

Works just fine with an un-modified version of this plugin and would apply to all plugins that need an alternate binary location. But there are other plugins which allow for defining an executable's path, such as https://github.com/bsnux/linter-python-pep8. So there is some precedent for what I proposed.

**Comment by Arcanemagus** [comment]
I'm hitting this on Windows as well. The system path already includes the Python executable, and forcing it to be (double) included as @henworth points out does not seem to change anything.

If it helps for comparison https://github.com/sadovnychyi/autocomplete-python is working just fine on this system with no path configuration necessary.

**Comment by tinloaf** [comment]
Hi! I'm sorry to reply so late, but I had hoped that this problem would vanish on it's own: This plugin has long been abandoned in favor of https://github.com/sadovnychyi/autocomplete-python ..

The Atom folks wanted to somehow mark my plugin as deprecated, but have not done so yet, as it seems. So, please switch over to that other one!
